DDCE-3539: Upgrade to scala 2.13
hmrc/currency-conversion pull request #66
Opened 2023-01-24 16:25 UTC by rreddy80

Upgrading currency-conversion from scala version 2.12 to 2.13

2023-01-30 12:42 UTC, EdCope requested changes
.right values can be removed [here](https://github.com/hmrc/currency-conversion/blob/main/app/uk/gov/hmrc/currencyconversion/binders/DateBinder.scala#L33-34)

2023-01-30 18:49 UTC, rreddy80 commented on project/AppDependencies.scala
>      "org.scalatestplus"       %% "mockito-3-4"         % "3.2.10.0",
done

2023-01-30 18:49 UTC, rreddy80 commented on test/uk/gov/hmrc/currencyconversion/workers/XrsExchangeRateRequestWorkerSpec.scala
> +  private val _dayOfMonth            = 26
removed the underscores now

2023-01-31 09:40 UTC, EdCope approved these changes

2023-01-31 09:41 UTC, merged