DDCE-4292: implement fallback mechanism for configurable number of months
hmrc/currency-conversion pull request #70
Opened 2023-06-14 18:34 UTC by rreddy80

fallback implementation

2023-06-19 16:16 UTC, lmugnai submitted a review, later dismissed

2023-06-19 16:16 UTC, lmugnai commented on app/uk/gov/hmrc/currencyconversion/repositories/ConversionRatePeriodJson.scala
> +    }
Can this be refactored? try and stay away from using mutable variables

2023-06-23 10:27 UTC, EdCope requested changes

2023-06-23 10:27 UTC, EdCope commented on test/uk/gov/hmrc/currencyconversion/controllers/ExchangeRateControllerSpec.scala
> +        Json.obj("startDate" -> "2019-12-01", "endDate" -> "2019-12-31", "currencyCode" -> "INR", "rate" -> "1.00")
These tests are now duplicated I don't think you need these

2023-06-23 10:34 UTC, rreddy80 commented on app/uk/gov/hmrc/currencyconversion/repositories/ConversionRatePeriodJson.scala
> +    }
Sorry forgot to reply to this. Done, Lorenzo

2023-06-23 11:12 UTC, rreddy80 commented on app/uk/gov/hmrc/currencyconversion/services/ExchangeRateService.scala
> +          s"XRS_FILE_NOT_AVAILABLE_ERROR [ConversionRatePeriodJson] No Exchange rate file is found with in the fallback period."
So this error is logged by ExchangeRateServie class only. Its not logged by any other class. why do we want to specify ConversionRatePeriodJson here? I have noticed some code where we unnecessarily specify the class name followed by a method name throwing error but in this case I felt its unnecessary as its all in the same class

2023-06-23 11:21 UTC, EdCope commented on app/uk/gov/hmrc/currencyconversion/services/ExchangeRateService.scala
> +          s"XRS_FILE_NOT_AVAILABLE_ERROR [ConversionRatePeriodJson] No Exchange rate file is found with in the fallback period."
Sorry you're right think i copied from below !
I meant 
[ExchangeRateService] [getCurrencies] XRS_FILE_NOT_AVAILABLE_ERROR - No Exchange rate file is found within the fallback period.

2023-06-23 11:21 UTC, rreddy80 commented on test/uk/gov/hmrc/currencyconversion/connectors/HODConnectorSpec.scala
> +    "must fall back to a 503 error when downstream throws a bad request" in {
this is to make sure all we return is a 503 irrespective of what the actual status is. There's a handler that handles bad requests (400 series). There's a dead code somewhere in the code that handles other errors, that needs to be removed as well in the future.

2023-06-23 11:22 UTC, mywyau commented on app/uk/gov/hmrc/currencyconversion/services/ExchangeRateService.scala
> +          s"XRS_FILE_NOT_AVAILABLE_ERROR [ConversionRatePeriodJson] No Exchange rate file is found with in the fallback period."
Hey we should probably just re write these logs to something like:

logger.error(s"[ExchangeRateService][getRates] XRS_FILE_NOT_AVAILABLE_ERROR  Unable to get ConversionRatePeriod - Exchange rate file is not available") 

logger.error(s"[ExchangeRateService][getCurrencies] XRS_FILE_NOT_AVAILABLE_ERROR  Unable to get CurrencyPeriod - Exchange rate file is not available")

Tells us the class and method and can easily search which branch of code is being executed when we see the logs in kibana. But as for formatting prefer the "[classname][method] your log message goes here"  

if this comment clears up anything

2023-06-23 11:27 UTC, mywyau commented on app/uk/gov/hmrc/currencyconversion/repositories/ConversionRatePeriodJson.scala
> +      val returnedFile = Await.result(checkFileExists(givenDate), Duration(maxWaitTime, SECONDS))
Not sure about blocking the Future and waiting for it. Does anyone know if we should be doing this? 

The recursion I think does not need the loop helper method as it's already tail recursive.

<img width="1173" alt="Screenshot 2023-06-23 at 12 26 20" src="https://github.com/hmrc/currency-conversion/assets/47248104/df6536d7-b445-4233-a631-7c43353d200d">

2023-06-23 16:11 UTC, rreddy80 commented on test/uk/gov/hmrc/currencyconversion/controllers/ExchangeRateControllerUnitSpec.scala
> +  val exchangeRateNew: Future[List[ExchangeRateResult]] = Future.successful(
deleted this file completely.

2023-06-23 16:12 UTC, rreddy80 commented on test/uk/gov/hmrc/currencyconversion/controllers/ExchangeRateControllerUnitSpec.scala
> +  "Getting rates for a date with no file received in the last 3 months and 1 valid currency" must {
this is no more used.

2023-06-26 11:34 UTC, EdCope approved these changes

2023-06-26 11:36 UTC, merged